# Generated by Django 2.0.8 on 2018-09-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('segment', models.CharField(max_length=140, null=True)),
                ('target', models.CharField(max_length=140, null=True)),
                ('file_path', models.ImageField(null=True, upload_to='')),
                ('incentive', models.FloatField(null=True)),
                ('difficulty', models.CharField(max_length=140, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
